<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    
    <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Debug'">
    
        <ItemGroup>
            <SeedDataFiles Include="$(ProjectDir)\Data\Seed\**" />
        </ItemGroup>
    
          <Message Text="Source files to copy: @(SeedDataFiles)" Importance="high" />
          <Message Text="Destination folder: $(OutDir)Seed" Importance="high" />
        <Copy SourceFiles="@(SeedDataFiles)" DestinationFolder="$(OutDir)Seed" Condition="%(Filename)!='' AND &#xD;&#xA;                (!Exists('$(OutDir)Seed\%(Filename)%(Extension)') OR &#xD;&#xA;                $([System.DateTime]::Parse('%(ModifiedTime)').Ticks) &gt; &#xD;&#xA;                $([System.IO.File]::GetLastWriteTime('$(OutDir)Seed\%(Filename)%(Extension)').Ticks))" />
    </Target>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.12.0" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageReference Include="ObservableCollections" Version="3.3.4" />
        <PackageReference Include="Xaml.Behaviors.Interactions" Version="12.0.0" />
        <PackageReference Include="Xaml.Behaviors.Interactions.Custom" Version="12.0.0" />
        <PackageReference Include="Xaml.Behaviors.Interactivity" Version="12.0.0" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Views\Dialogs\AddSentenceDialog.axaml" />
      <AdditionalFiles Include="Views\Dialogs\EditTranslationDialog.axaml" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\TranslationsView.axaml.cs">
        <DependentUpon>SentenceView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\WordsView.axaml.cs">
        <DependentUpon>WordView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\RunesView.axaml.cs">
        <DependentUpon>RuneView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
