<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>preview</LangVersion>
        <UseAppHost>true</UseAppHost>
        <ApplicationIcon>Assets/Descript.ico</ApplicationIcon>
        
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>false</SelfContained>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    </PropertyGroup>
    
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
      <DebugType>None</DebugType>
      <DebugSymbols>False</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>
    
    <Target Name="CopyCustomContent" AfterTargets="AfterBuild" Condition="'$(Configuration)' == 'Debug'">
    
        <ItemGroup>
            <SeedDataFiles Include="$(ProjectDir)\Data\Seed\**" />
        </ItemGroup>
    
          <Message Text="Source files to copy: @(SeedDataFiles)" Importance="high" />
          <Message Text="Destination folder: $(OutDir)Seed" Importance="high" />
        <Copy SourceFiles="@(SeedDataFiles)" DestinationFolder="$(OutDir)Seed" Condition="%(Filename)!='' AND &#xD;&#xA;                (!Exists('$(OutDir)Seed\%(Filename)%(Extension)') OR &#xD;&#xA;                $([System.DateTime]::Parse('%(ModifiedTime)').Ticks) &gt; &#xD;&#xA;                $([System.IO.File]::GetLastWriteTime('$(OutDir)Seed\%(Filename)%(Extension)').Ticks))" />
    </Target>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.2" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.12.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\ViewSentences.axaml.cs">
        <DependentUpon>SentenceView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ViewPhrases.axaml.cs">
        <DependentUpon>WordView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ViewElements.axaml.cs">
        <DependentUpon>RuneView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Dialogs\DialogPhrase.axaml.cs">
        <DependentUpon>EditRuneChainDialog.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Elements\ElementListItem.axaml.cs">
        <DependentUpon>ElementListItem.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Elements\PhraseListItem.axaml.cs">
        <DependentUpon>PhraseListItem.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\Elements\SentenceListItem.axaml.cs">
        <DependentUpon>TranslationLine.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
